// Generated by Wrangler by running `wrangler types`

interface Env {
  LINE_RECEIPIENT_IDS: string[];
  LINE_RECEIPIENT_ID: string;
  LINE_ADMIN_RECEIPIENT_ID: string;
  LINE_CHANNEL_ACCESS_TOKEN: string;
}
