name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

env:
  NODE_VERSION: 22.x
  PNPM_VERSION: 10

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env
      - run: pnpm tsc --noEmit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env
      - run: pnpm eslint .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy wrangler config from template
        run: cp wrangler.toml.example wrangler.toml
      - uses: ./.github/actions/setup-pnpm-env
      - run: pnpm vitest --run --passWithNoTests --coverage
